# Generated by Django 5.2.13 on 2026-06-03 05:45

import django.core.validators
import django.db.models.deletion
import savings.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SavingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration_months', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('is_flexible', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_flexible', True), ('duration_months__isnull', True)), models.Q(('is_flexible', False), ('duration_months__isnull', False)), _connector='OR'), name='savingtype_duration_matches_flexibility')],
            },
        ),
        migrations.CreateModel(
            name='SavingPlan',
            fields=[
                ('plan_id', models.CharField(default=savings.models.generate_plan_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='PENDING', max_length=10)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('interest_last_applied_on', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saving_plans', to='users.customer')),
                ('saving_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saving_plans', to='savings.savingtype')),
            ],
        ),
        migrations.CreateModel(
            name='SavingTypeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('saving_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='savings.savingtype')),
            ],
            options={
                'ordering': ['effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('OPEN', 'Saving Plan Opening'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdrawal'), ('CLOSE', 'Saving Plan Closing')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('saving_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='savings.savingplan')),
            ],
        ),
        migrations.AddConstraint(
            model_name='savingplan',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='savingplan_balance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('transaction_type__in', ['DEPOSIT', 'WITHDRAW'])), models.Q(('amount__gte', 0), ('transaction_type__in', ['OPEN', 'CLOSE'])), _connector='OR'), name='transaction_amount_positive_for_deposit_withdraw'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('balance_before__gte', 0), ('balance_after__gte', 0)), name='transaction_balances_nonnegative'),
        ),
    ]
