# Generated by Django 5.2.14 on 2026-06-03 12:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_create_default_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingplan',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
