# Generated by Django 5.2.13 on 2026-05-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_create_default_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingplan',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('CANCELED', 'Canceled')], default='SUCCESS', max_length=10),
            preserve_default=False,
        ),
    ]
