# Generated by Django 5.2.14 on 2026-06-05 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_alter_savingplan_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingtype',
            name='duration_months',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
