# Generated by Django 5.2.13 on 2026-05-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_savingplan_is_pending_transaction_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingplan',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='savingplan',
            name='is_pending',
        ),
        migrations.AddField(
            model_name='savingplan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='PENDING', max_length=10),
        ),
    ]
