# Generated by Django 5.2.13 on 2026-05-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_remove_savingplan_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='savingplan',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
