# Generated by Django 6.0.5 on 2026-06-02 14:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_rename_transaction_status_transaction_status_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingplan',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='savingplan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='savingplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savingtype',
            name='duration_months',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='savingtype',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='savingtyperatehistory',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='savingplan',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='savingplan_balance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='savingtype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_flexible', True), ('duration_months__isnull', True)), models.Q(('is_flexible', False), ('duration_months__isnull', False)), _connector='OR'), name='savingtype_duration_matches_flexibility'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('transaction_type__in', ['DEPOSIT', 'WITHDRAW'])), models.Q(('amount__gte', 0), ('transaction_type__in', ['OPEN', 'CLOSE'])), _connector='OR'), name='transaction_amount_positive_for_deposit_withdraw'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('balance_before__gte', 0), ('balance_after__gte', 0)), name='transaction_balances_nonnegative'),
        ),
    ]
